[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  
[build]
  command = "npm run build"  # Comando para construir tu proyecto React
  functions = "functions"    # Directorio que contiene tus funciones de Netlify
  publish = "build"       

[functions]
  directory = ".netlify/functions"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "dist" 
  autoLaunch = true
  framework = "create-react-app"